config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users , controllers: { registrations: 'registrations'}
  resources :products
  resources :categories
  resources :brands
  resources :orders
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one 
  end
  root 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :products, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :order_product
    has_many :products, through: :order_product
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_one_attached :image
    belongs_to :brand
    has_many :orders, through: :order_product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :orders
        def current_user_cart
          "cart#{id}"
        end

        def add_to_cart(product_id)
          $redis.hincrby current_user_cart, product_id, 1
        end
          
        def remove_from_cart(product_id)
          $redis.hdel current_user_cart, product_id
        end

        def remove_one_from_cart(product_id)
          $redis.hincrby current_user_cart, product_id, -1
        end

        def cart_count
          quantities = $redis.hvals "cart#{id}"
          quantities.reduce(0) { |sum, qty| sum + qty.to_i}
        end

        def cart_total_price
          get_cart_products_with_qty.map { |product, qty| product.price * qty.to_i }.reduce(:+)
        end
        def order_now
          @order= Order.new
        end
        def get_cart_products_with_qty
          cart_ids = []
          cart_qtys = []
          ($redis.hgetall current_user_cart).map do |key, value|
            cart_ids << key
            cart_qtys << value
          end
          cart_products = Product.find(cart_ids)
          cart_products.zip(cart_qtys)
        end

        def purchase_cart_products!
          get_cart_products_with_qty.each do |product, qty|
            self.orders.create(user: self, product: product, quantity: qty)
          end
          $redis.del current_user_cart
        end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :authenticate_admin!
    def new
        @brand= Brand.new
    end
    def create
        @brand = Brand.new(params.require(:brand).permit(:name))
        @brand.save
        redirect_to :controller => 'products', :action => 'index'
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!

  def show
    @cart_products_with_qty = current_user.get_cart_products_with_qty
    @cart_total = current_user.cart_total_price
  end

  def add
    current_user.add_to_cart(params[:product_id])
    redirect_to cart_path
  end

  def remove
    current_user.remove_from_cart(params[:product_id])
    redirect_to cart_path
  end

  def removeone
    current_user.remove_one_from_cart(params[:product_id])
    redirect_to cart_path
  end
  private

  def current_user_cart
    "cart#{current_user.id}"
  end

  def cart_count
  $redis.scard "cart#{id}"
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_admin!
    def show
    end
    #this to add new book
    def new
        @category= Category.new
    end
    def create
        @category = Category.new(params.require(:category).permit(:name))
        @category.save
        redirect_to :controller => 'products', :action => 'index'
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


    before_action :authenticate_user!
    def create
        @order=Order.new(params.require(:order).permit(:user_id).merge!({status: 'Ordered'}))
        @order.save
        redirect_to :controller => 'products', :action => 'index'
    end
        
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    #this main page where we view all products
    def index
        @products=Product.all.with_attached_image
    end
    #this to show product under certain category
    def show
        @product=Product.find(params[:id])
    end
    #this to add new book
    def new
        @product=Product.new
        @categories=Category.all
        @brands=Brand.all
    end
    #this to ad new book
    def create
        @product=Product.new(params.require(:product).permit(:title, :description, :price, :in_stock, :category_id, :brand_id, :image ))
        @product.save
        redirect_to :controller => 'products', :action => 'index'
        
    end 

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
    private

    def sign_up_params
        params.require(:user).permit(:name ,:email,:password ,:password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name ,:email ,:password ,:password_confirmation,:current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/brands/_form.html.erb
<div class="container">
<%= form_with model: @brand, local: true do |form| %>
 
    <% if @brand.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@brand.errors.count, "error") %> prohibited
          this brand from being saved:
        </h2>
        <ul>
          <% @brand.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.submit %>
    </p>
   
  <% end %>
  </div>

app/views/brands/new.html.erb
<div class="container">
<h1>New Brand</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', products_path %>
</div>

app/views/carts/show.html.erb
<div class="container">
<h1>Ur shopping cart</h1>


<div class="row">
<table class="table">
   <thread>
     <th>Name</th>
     <th>Price</th>
     <th>Quantity</th>
     <th>subTotal</th>
     <tbody>
     <% @cart_products_with_qty.each do |array| %>
        <% product = array[0]%>
        <%qty = array[1]%>
    <tr>
    <td><%= product.title%></td>
    <td><%= product.price%></td>
    <td><%= qty%></td>
    <td><%= product.price * qty.to_i %></td>
    <td>
    <% if qty.to_i < product.in_stock.to_i  %>
    
    <%= link_to '+', add_to_cart_path(product), method: :put, class: "btn"%>
     <%end%>   
    <%= link_to '-', remove_one_cart_path(product), method: :put, class: "btn"%>
    <%= link_to 'Remove', remove_from_cart_path(product), method: :put, class: "btn btn-danger"%>
      <% @order.user_id = current_user %>
      <% @order.status ='Ordered'%>
       </tr>
       <%end%>
       <tr >
       <td colspan="3"> <h5>Total</h5></td>
       <td><h5><%= @cart_total%></h5></td></tr>
       </tbody>
       </table>
       <%= link_to 'Products', products_path%>
       <div style="float:right">
       <%= link_to 'Order Now', orders_path(:order => @order), method: :post %>
       </div>

app/views/categories/_form.html.erb
<div class="container">
<%= form_with model: @category, local: true do |form| %>
 
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@category.errors.count, "error") %> prohibited
          this category from being saved:
        </h2>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.submit %>
    </p>
   
  <% end %>
  </div>

app/views/categories/new.html.erb
<div class="container">
<h1>New Category</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', products_path %>
</div>

app/views/products/_form.html.erb
<div class="container">
<%= form_with model: @product, local: true do |form| %>
 
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@product.errors.count, "error") %> prohibited
          this product from being saved:
        </h2>
        <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
    <%= form.label :image%><br>
    <%= form.file_field :image%>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.label :price %><br>
      <%= form.text_field :price %>
    </p>

    <p>
      <%= form.label :in_stock %><br>
      <%= form.text_field :in_stock %>
    </p>
  <p>
    <%= form.label :category_id %><br />
    <%= collection_select(:product, :category_id, @categories, :id, :name, {:prompt => false}) %>
   </p>
   <p>
   <%= form.label :brand_id %><br />
    <%= collection_select(:product, :brand_id, @brands, :id, :name, {:prompt => false}) %>
    </p>
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>
  </div>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<div class="container">
<div class="row">
<% @products.each do |product| %>
<div class="col-3 ml-3" >
        <div class="card">
        <div class="card-img-top">
        <%= image_tag(url_for(product.image),width: '180px',height: '150px') if product.image.attached?%></div>
        <div class="card-body">
          <h5 class="card-title"><%=product.title%></h5>
          <p class="card-text"><%=product.description%></p>
          <p><span style="color :blue"><%=product.brand.name%>  </span><span style="color:red;float:right;"><%=product.category.name%></p>
          <%if signed_in?%>
          <%= link_to 'show product details', product_path(product.id)%>
          <%end%>
          </div>
      </div>
        </div>
    <% end %>
      
      </div>
</div>

app/views/products/new.html.erb
<div class="container">
<h1>New Product</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">
<div class="row">
<div class="col-6" >
        <div class="card">
        <div class="card-img-top">
        <%= image_tag(url_for(@product.image),width: '280px',height: '250px') if @product.image.attached?%></div>
        <div class="card-body">
          <h5 class="card-title"><%=@product.title%></h5>
          <p class="card-text"><%=@product.description%></p>
          <p><span style="color :blue"><%=@product.brand.name%>  </span><span style="color:red;float:right;"><%=@product.category.name%></p>
          <%if signed_in?%>
         <%= link_to 'Add to cart', add_to_cart_path(@product.id), method: :put%><br>
         <%= link_to 'Back to products', products_path%>
       <%end%>
          </div>
      </div>
        </div>
      </div>
</div>